version: "3.8"
services:
  backend:
    build: ./be
    ports:
      - "8000:8000"
    env_file:
      - ./be/.env
  frontend:
    build:
      context: ./fe
      args:
        - NEXT_PUBLIC_BASE_URL=http://localhost:8000
    ports:
      - "3000:3000"
    env_file:
      - ./fe/.env
