import { Metadata } from "next";
import React from "react";
export const metadata: Metadata = {
  title: "JK Keyboard - Product",
  description: "Generated by create next app",
};
export default function Layout({ children }: { children: React.ReactNode }) {
  return <>{children}</>;
}
